# Generated by Django 6.0.2 on 2026-07-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_order_quote_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='dual_pricing',
            field=models.BooleanField(default=False, help_text='Mostra preços de varejo e atacado lado a lado.', verbose_name='Orçamento Atacado + Varejo'),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='unit_value_wholesale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Unit. Atacado'),
        ),
    ]
