# Generated by Django 6.0.2 on 2026-07-27 12:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_quote_dual_pricing_quoteitem_unit_value_wholesale'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='commission_calculated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Comissão apurada em'),
        ),
        migrations.AddField(
            model_name='quote',
            name='commission_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Comissão (%)'),
        ),
        migrations.AddField(
            model_name='quote',
            name='commission_source',
            field=models.CharField(blank=True, choices=[('ENGINE', 'Apurada no fechamento'), ('BACKFILL', 'Estimada retroativamente')], default='', max_length=10, verbose_name='Origem da comissão'),
        ),
        migrations.AddField(
            model_name='quote',
            name='commission_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Comissão (R$)'),
        ),
        migrations.AddField(
            model_name='quote',
            name='down_payment_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Entrada (R$)'),
        ),
    ]
