# Generated by Django 6.0.2 on 2026-07-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_credit_card_tiered_tariffs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenttariff",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("CASH", "Dinheiro"),
                    ("PIX", "PIX"),
                    ("DEBIT_CARD", "Cartão de Débito"),
                    ("CREDIT_CARD", "Cartão de Crédito"),
                    ("CHEQUE", "Cheque"),
                    ("BOLETO", "Boleto"),
                    ("BOLETO_30", "Boleto para 30 dias"),
                ],
                help_text="Tipo do método de pagamento",
                max_length=20,
                verbose_name="Tipo de Pagamento",
            ),
        ),
    ]
